Add new Installer with FHS pattern
Some changes were made to the distro:

- The grub menu now correctly shows
  "Tortoise Linux" among the options

- os-release is updated with tortoise
  information

- Zsh is the default shell now

- Oh-my-zsh is pre-configurated

- Picom added and pre-configurated

- Now we have some default wallpapers

- The user is now correctly placed in sudoers.

- It is now easier to deploy the installer
  to the distro automatically.

- A function to update the installer even on
  an old ISO that is updated and working fine.

diff --git a/profile/airootfs/usr/local/bin/egginstall b/profile/airootfs/usr/local/bin/egginstall
--- a/profile/airootfs/usr/local/bin/egginstall
+++ b/profile/airootfs/usr/local/bin/egginstall
@@ -1,1 +1,64 @@
-/etc/tortoise/tortoise_installer/install.sh
+#!/usr/bin/env bash
+#========================{HEADER}========================|
+#AUTHOR: wellyton 'welly' <welly.tohn@gmail.com>
+#PROGRAM: install.sh 
+#DESCRIPTION: Instalador do tortoise
+#LICENSE: MIT
+#========================{ END }=========================|
+
+set -ex
+
+source /usr/lib/tortoise/lib.sh
+source /var/cache/tortoise/progress
+source /etc/tortoise/egginstall.conf
+
+HELP="
+$(basename $0) {OPTION}
+This script make system installation using config file
+generated by `configure.sh`
+Remember to use configure before run this script, always.
+
+commands:
+   $(basename $0) -{command}
+    h | help
+    NOTE: (-) or (--) before commands is optional
+"
+
+case $1 in
+    h | -h | help | --help)
+        print "$HELP"
+	;;
+esac
+
+[[ -v INSTALLFILE ]] || INSTALLFILE="/home/turtle/install.conf"
+
+source "$INSTALLFILE"
+
+HOME=""
+
+# criar um cache para as etapas de instalação abaixo
+
+set_keyboard "$KEYBOARD"
+
+make_ext4 "$ROOT"
+
+make_swap "$SWAP"
+
+make_efi "$EFI"
+
+print "mounting filesystem"
+
+mount_root "$ROOT"
+
+mount_efi "$EFI"
+
+mount_swap "$SWAP"
+
+install_packages || error "Error when installing packages"
+
+gen_fstab
+
+copy_config_files || error "Error when trying to copy config files" 
+
+print "join into system with arch-chroot"
+post_install || error "Error when running post install commands"
